USE tc_la_revista;

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    CATEGORIA VARCHAR(30) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    FECHAS INT NOT NULL DEFAULT 0,
    CIRCUITOS INT NOT NULL DEFAULT 0,
    PILOTOS INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE CIRCUITOS (
    ID_CIRCUITO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CIRCUITO VARCHAR(50) NOT NULL,
    UBICACION VARCHAR(50) NOT NULL,
    LONGITUD DECIMAL(5, 2),
    ID_CATEGORIA INT NOT NULL,
    PRIMARY KEY (ID_CIRCUITO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE PILOTOS (
    ID_PILOTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    NACIONALIDAD VARCHAR(30) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    MARCA VARCHAR(30),
    PRIMARY KEY (ID_PILOTO)
);

CREATE TABLE PILOTO_CATEGORIA (
    ID_PILOTO INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    PRIMARY KEY (ID_PILOTO, ID_CATEGORIA),
    FOREIGN KEY (ID_PILOTO) REFERENCES PILOTOS(ID_PILOTO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE CAMPEONATOS (
    ID_CAMPEONATO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CAMPEONATO VARCHAR(50),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    TIPO_CAMPEONATO VARCHAR(30),
    PRIMARY KEY (ID_CAMPEONATO)
);

CREATE TABLE RESULTADOS_CAMPEONATO (
    ID_CAMPEONATO INT NOT NULL,
    ID_PILOTO INT NOT NULL,
    PUNTOS INT,
    VICTORIAS INT,
    MARCA VARCHAR(30),
    PRIMARY KEY (ID_CAMPEONATO, ID_PILOTO),
    FOREIGN KEY (ID_CAMPEONATO) REFERENCES CAMPEONATOS(ID_CAMPEONATO),
    FOREIGN KEY (ID_PILOTO) REFERENCES PILOTOS(ID_PILOTO)
);

CREATE TABLE FECHAS (
    ID_FECHA INT NOT NULL AUTO_INCREMENT,
    ID_CAMPEONATO INT,
    PUNTOS INT,
    VICTORIAS INT,
    MARCA VARCHAR(30),
    PRIMARY KEY (ID_FECHA),
    FOREIGN KEY (ID_CAMPEONATO) REFERENCES CAMPEONATOS(ID_CAMPEONATO)
);
